import type { LearningCatalogLesson } from "@/types/learning-catalog"

export interface CesiumCatalogLesson extends LearningCatalogLesson {
  api: string
}

export const cesiumLessons: CesiumCatalogLesson[] = [
  {
    routeName: "CesiumEntry",
    title: "01-Viewer 与场景初始化",
    path: "/cesium-demo/cesium-entry",
    component: () => import("./01-cesium-entry.vue"),
    summary: "创建 Viewer，配置场景与基础控件。",
    api: "Viewer · Scene",
    thumbnail: "/cesium-data/lesson-thumbnails/01-viewer-scene.png",
  },
  {
    routeName: "CesiumCoordinates",
    title: "02-坐标转换与相机方位",
    path: "/cesium-demo/coordinates",
    component: () => import("./02-cesium-coordinates.vue"),
    summary: "在经纬度、笛卡尔坐标与相机方位之间转换。",
    api: "Cartesian3 · Camera",
    thumbnail: "/cesium-data/lesson-thumbnails/02-coordinates-camera.png",
  },
  {
    routeName: "CesiumEvents",
    title: "03-屏幕空间事件",
    path: "/cesium-demo/events",
    component: () => import("./03-cesium-events.vue"),
    summary: "响应鼠标输入并获取场景交互结果。",
    api: "ScreenSpaceEventHandler",
    thumbnail: "/cesium-data/lesson-thumbnails/03-screen-space-events.png",
  },
  {
    routeName: "CesiumEntity",
    title: "04-Entity 图形与属性",
    path: "/cesium-demo/entity",
    component: () => import("./04-cesium-entity.vue"),
    summary: "用高层对象描述点、线、面与样式，含 EntityCluster 点聚合。",
    api: "Entity · Graphics · EntityCluster",
    thumbnail: "/cesium-data/lesson-thumbnails/04-entity-graphics.png",
  },
  {
    routeName: "CesiumPrimitive",
    title: "05-Primitive 与几何实例",
    path: "/cesium-demo/primitive",
    component: () => import("./05-cesium-primitive.vue"),
    summary: "理解 GeometryInstance 与 Primitive 的渲染组织。",
    api: "Primitive · GeometryInstance",
    thumbnail: "/cesium-data/lesson-thumbnails/05-primitive-geometry.png",
  },
  {
    routeName: "CesiumData",
    title: "06-数据源与三维数据加载",
    path: "/cesium-demo/data",
    component: () => import("./06-cesium-data.vue"),
    summary: "加载 GeoJSON、CZML、glTF 模型和三维瓦片。",
    api: "DataSource · Model · Cesium3DTileset",
    thumbnail: "/cesium-data/lesson-thumbnails/06-data-3d.png",
  },
  {
    routeName: "Cesium3DTiles",
    title: "07-3DTileset：加载、样式与拾取",
    path: "/cesium-demo/3dtiles",
    component: () => import("./07-cesium-3dtiles.vue"),
    summary: "浏览大规模三维瓦片，控制样式、拾取和性能。",
    api: "Cesium3DTileset · Cesium3DTileStyle",
    thumbnail: "/cesium-data/lesson-thumbnails/07-3dtileset.png",
  },
  {
    routeName: "CesiumTimeline",
    title: "08-Clock 与动态轨迹",
    path: "/cesium-demo/timeline",
    component: () => import("./08-cesium-timeline.vue"),
    summary: "让时钟驱动模型、轨迹和相机跟随。",
    api: "Clock · SampledPositionProperty",
    thumbnail: "/cesium-data/lesson-thumbnails/08-clock-trajectory.png",
  },
  {
    routeName: "CesiumDrawMeasure",
    title: "09-交互绘制与量算",
    path: "/cesium-demo/draw-measure",
    component: () => import("./09-cesium-draw-measure.vue"),
    summary: "交互生成 Entity，并完成距离与面积量算。",
    api: "Entity · ScreenSpaceEventHandler",
    thumbnail: "/cesium-data/lesson-thumbnails/09-entity-draw-measure.png",
  },
  {
    routeName: "CesiumTerrainAnalysis",
    title: "10-地形采样与空间分析",
    path: "/cesium-demo/terrain-analysis",
    component: () => import("./10-cesium-terrain-analysis.vue"),
    summary: "对地形进行高程、剖面、通视和坡度分析。",
    api: "sampleTerrainMostDetailed · Cartographic",
    thumbnail: "/cesium-data/lesson-thumbnails/10-terrain-analysis.png",
  },
  {
    routeName: "CesiumMaterialEffects",
    title: "11-Entity 动态材质",
    path: "/cesium-demo/material-effects",
    component: () => import("./11-cesium-material-effects.vue"),
    summary: "通过 Entity 的 material 属性构建流光、动态墙与扩散效果。",
    api: "Entity · MaterialProperty",
    thumbnail: "/cesium-data/lesson-thumbnails/11-entity-material.png",
  },
  {
    routeName: "CesiumCustomShader",
    title: "12-Model 与 3D Tiles 的 CustomShader",
    path: "/cesium-demo/custom-shader",
    component: () => import("./12-cesium-custom-shader.vue"),
    summary: "为 glTF 模型和三维瓦片注入自定义着色逻辑。",
    api: "CustomShader · Model · Cesium3DTileset",
    thumbnail: "/cesium-data/lesson-thumbnails/12-custom-shader.png",
  },
  {
    routeName: "CesiumCustomAppearance",
    title: "13-Primitive 与 Appearance",
    path: "/cesium-demo/custom-appearance",
    component: () => import("./13-cesium-custom-appearance.vue"),
    summary: "从几何属性到 GLSL，控制 Primitive 的渲染入口。",
    api: "Primitive · Appearance",
    thumbnail: "/cesium-data/lesson-thumbnails/13-primitive-appearance.png",
  },
  {
    routeName: "CesiumSceneEnvironment",
    title: "14-Scene 环境与出图",
    path: "/cesium-demo/scene-environment",
    component: () => import("./14-cesium-scene-environment.vue"),
    summary: "控制天空、雾效、场景模式与画布导出。",
    api: "Scene · SkyBox · Canvas",
    thumbnail: "/cesium-data/lesson-thumbnails/14-scene-environment.png",
  },
  {
    routeName: "CesiumLayerManagement",
    title: "15-图层体系与图层树管理",
    path: "/cesium-demo/layer-management",
    component: () => import("./15-cesium-layer-management.vue"),
    summary: "用前端图层树组织影像、数据源、Entity 与 3D Tiles。",
    api: "ImageryLayerCollection · DataSourceCollection · PrimitiveCollection",
    thumbnail: "/cesium-data/lesson-thumbnails/15-layer-management.png",
  },
  {
    routeName: "CesiumAnnotationEdit",
    title: "16-前端标绘编辑与 GeoJSON 导出",
    path: "/cesium-demo/annotation-edit",
    component: () => import("./16-cesium-annotation-edit.vue"),
    summary: "创建并编辑点线面，在浏览器中导出标准 GeoJSON。",
    api: "Entity · ScreenSpaceEventHandler · GeoJSON",
    thumbnail: "/cesium-data/lesson-thumbnails/16-annotation-edit.png",
  },
  {
    routeName: "CesiumPerformanceLifecycle",
    title: "17-性能优化与资源生命周期",
    path: "/cesium-demo/performance-lifecycle",
    component: () => import("./17-cesium-performance-lifecycle.vue"),
    summary: "用按需渲染、事件清理和销毁顺序治理前端场景。",
    api: "Scene.requestRenderMode · Viewer.destroy",
    thumbnail: "/cesium-data/lesson-thumbnails/17-performance-lifecycle.png",
  },
  {
    routeName: "CesiumParticleSystem",
    title: "18-粒子系统",
    path: "/cesium-demo/particle-system",
    component: () => import("./18-cesium-particle-system.vue"),
    summary: "火焰、烟雾、爆炸等粒子效果与四种内置发射器。",
    api: "ParticleSystem · ParticleEmitter",
    thumbnail: "/cesium-data/lesson-thumbnails/placeholder.svg",
  },
  {
    routeName: "CesiumClippingFlood",
    title: "19-裁剪与淹没分析",
    path: "/cesium-demo/clipping-flood",
    component: () => import("./19-cesium-clipping-flood.vue"),
    summary: "裁剪平面透视地下与建筑剖面，交互式淹没模拟。",
    api: "ClippingPlaneCollection · CallbackProperty",
    thumbnail: "/cesium-data/lesson-thumbnails/placeholder.svg",
  },
]
